name: Auto-tag release from pyproject

on:
  push:
    branches: [ main ]
    paths:
      - 'pyproject.toml'

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Read version from pyproject.toml
        id: get_version
        run: |
          VER=$(grep -E '^version\s*=\s*"' pyproject.toml | head -1 | sed -E 's/.*"([^\"]+)".*/\1/')
          echo "Found version: $VER"
          if [ -z "$VER" ]; then
            echo "::error::Could not parse version from pyproject.toml"
            exit 1
          fi
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Check tag exists on remote
        run: |
          VER=${{ steps.get_version.outputs.version }}
          echo "Checking for tag: $VER"
          git fetch --tags
          if git ls-remote --tags origin | awk '{print $2}' | grep -q "refs/tags/$VER$"; then
            echo "Tag $VER already exists on remote; skipping tag creation."
            exit 0
          fi

      - name: Create and push tag
        if: steps.get_version.outputs.version != ''
        run: |
          VER=${{ steps.get_version.outputs.version }}
          echo "Creating tag $VER"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$VER" -m "Release $VER"
          # If a repo PAT is provided as the secret REPO_PAT, use it to push so the push will trigger other workflows.
          if [ -n "${{ secrets.REPO_PAT }}" ]; then
            echo "Pushing tag using REPO_PAT (will trigger other workflows)."
            git remote set-url origin https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }}.git
            git push origin "$VER"
          else
            echo "REPO_PAT secret not found. Pushing with default credentials (GITHUB_TOKEN) — note: pushes made with GITHUB_TOKEN do NOT trigger downstream workflows."
            git push origin "$VER"
          fi
