name: Publish Python 🐍 distribution to PyPI

on:
    push:
      tags:
        - '*.*.*'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Verify tag matches pyproject version and sync core VERSION
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG"
          PYV=$(grep -E '^version\s*=\s*"' pyproject.toml | head -1 | sed -E 's/.*"([^\"]+)".*/\1/')
          echo "pyproject version: $PYV"
          if [ "${TAG}" != "${PYV}" ]; then
            echo "::error::Tag ($TAG) does not match pyproject.toml version ($PYV). Bump pyproject.toml version and/or push the correct tag."
            exit 1
          fi
          # Set core.py VERSION to have the v prefix used at runtime (v<version>)
          sed -E -i "s/^VERSION = .*$/VERSION = \"v${PYV}\"/" src/wdin/core.py
          head -n 6 src/wdin/core.py
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
