name: Publish Python 🐍 distribution to PyPI

on:
    push:
      tags:
        - '*.*.*'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update VERSION in core.py to match tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          sed -i "s/^VERSION = \".*\"/VERSION = \"$TAG_NAME\"/" src/wdin/core.py
          head -10 src/wdin/core.py
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
